package shadow.plugin.util;

public abstract interface ShadowData
{
  public static final int[] PREFIXES = {
    10, 
    'b', 2, 'B', 2, 
    'c', 8, 'C', 8, 
    'x', 16, 'x', 16 };
  public static final String[] INTEGRAL_SUFFIXES = {
    "", 
    "y", "uy", "Y", "UY", "uY", "Uy", 
    "s", "us", "S", "US", "uS", "Us", 
    "i", "u", "ui", "I", "U", "UI", "uI", "Ui",
    "l", "ul", "L", "UL", "uL", "Ul" };
  public static final String[] DECIMAL_SUFFIXES = {
    "", 
    "f", "F", 
    "d", "D" };
  public static final String[] LITERALS = {
    "true", 
    "false", 
    "null" };
  public static final String[] TYPES = {
    "boolean", 
    "byte", 
    "code", 
    "double", 
    "float", 
    "int", 
    "long", 
    "short", 
    "ubyte", 
    "uint", 
    "ulong", 
    "ushort", 
    "var" };
  public static final String[] KEYWORDS = {
	  "abstract",
	  "and",
	  "assert",	  
	  "break",	  
	  "case",
	  "cast",
	  "catch",
	  "check",
	  "class",	  
	  "copy",
	  "create",
	  "constant",
	  "continue",
	  "default",
	  "destroy",
	  "do",	  
	  "else",
	  "enum",	  
	  "exception",
	  "extends",
	  "false",
	  "finally",	  
	  "for",
	  "foreach",
	  "freeze",
	  "get",
	  "if",
	  "immutable",
	  "implements",
	  "import",
	  "in",	  
	  "is",	  
	  "interface",
	  "locked",	  
	  "native",
	  "null",
	  "nullable",
	  "or",
	  "private",
	  "protected",
	  "public",
	  "readonly",
	  "recover",
	  "return",
	  "set",	  
	  "singleton",
	  "skip",
	  "super",
	  "switch",
	  "this",
	  "throw",
	  "throws",
	  "true",
	  "try",	  
	  "weak",
	  "while",
	  "xor" };
}
